# Generated by Django 5.2.8 on 2025-11-24 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/images/",
                verbose_name="Product Image",
            ),
        ),
    ]
